[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.67.1"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify -D -E -F -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -D -E -F -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
