---
new_page_extension: md
auto_deploy: false
admin_path: static/redac
webhook_url: ''
sections:
- type: directory
  path: content/post
  label: Articles
  create: all
  match: "**/*"
  templates:
  - post
- type: document
  path: config.yaml
  label: Configuration
upload_dir: ''
public_path: ''
front_matter_path: https://res.cloudinary.com/jamstatic/image/upload/c_scale,f_auto,q_auto,w_1200
use_front_matter_path: true
file_template: 'https://res.cloudinary.com/jamstatic/image/upload/c_scale,f_auto,q_auto,w_1028/:filename:'
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.70.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.70.0
